# SciKit Learn Preprocessing Overview

In [1]:
import numpy as np

In [2]:
from sklearn.preprocessing import MinMaxScaler

In [3]:
data = np.random.randint(0,100,(10,2))

In [4]:
data

array([[72, 42],
       [81, 51],
       [93, 91],
       [ 7, 16],
       [83, 15],
       [ 5, 42],
       [48, 81],
       [57, 28],
       [58, 19],
       [14, 65]])

In [5]:
scaler_model = MinMaxScaler()

In [6]:
scaler_model.fit(data)

C:\Users\nickos\Anaconda3\envs\ml\lib\site-packages\sklearn\utils\validation.py:444: DataConversionWarning: Data with input dtype int32 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


MinMaxScaler(copy=True, feature_range=(0, 1))

In [7]:
scaler_model.transform(data)

array([[ 0.76136364,  0.35526316],
       [ 0.86363636,  0.47368421],
       [ 1.        ,  1.        ],
       [ 0.02272727,  0.01315789],
       [ 0.88636364,  0.        ],
       [ 0.        ,  0.35526316],
       [ 0.48863636,  0.86842105],
       [ 0.59090909,  0.17105263],
       [ 0.60227273,  0.05263158],
       [ 0.10227273,  0.65789474]])

In [8]:
# In one step
result = scaler_model.fit_transform(data)

C:\Users\nickos\Anaconda3\envs\ml\lib\site-packages\sklearn\utils\validation.py:444: DataConversionWarning: Data with input dtype int32 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


In [9]:
result

array([[ 0.76136364,  0.35526316],
       [ 0.86363636,  0.47368421],
       [ 1.        ,  1.        ],
       [ 0.02272727,  0.01315789],
       [ 0.88636364,  0.        ],
       [ 0.        ,  0.35526316],
       [ 0.48863636,  0.86842105],
       [ 0.59090909,  0.17105263],
       [ 0.60227273,  0.05263158],
       [ 0.10227273,  0.65789474]])

In [10]:
import pandas as pd

In [11]:
data = pd.DataFrame(data=np.random.randint(0,101,(50,4)),columns=['f1','f2','f3','label'])

In [12]:
data.head()

f1  f2  f3  label
0  15  67  68      8
1  60  71  14      9
2  52  59  44     16
3  48   6  54     60
4  90   5  20     60

In [15]:
x = data[['f1','f2','f3']].values.tolist() # Alternatively x = data.drop('label',axis=1)
y = data['label'] 

if len(x) == len(y):
    print("data is ok go for ML")

data is ok go for ML


In [26]:
from sklearn.model_selection import train_test_split

In [27]:
X_train, X_test, y_train, y_test = train_test_split(x,y,test_size=0.3,random_state=101)

In [28]:
X_train.shape

(35, 3)

In [29]:
X_test.shape

(15, 3)

In [30]:
y_train.shape

(35,)

In [31]:
y_test.shape

(15,)

## Great Job!